CREATE TABLE [dbo].[ApplicationData](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](2000) NULL,
	[Value] [nvarchar](2000) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


