//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EudoxusOsy.BusinessModel.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EudoxusOsy.BusinessModel.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ηλεκτρονική Κοστολόγηση.
        /// </summary>
        internal static string enBookApplicationType_ElectronicPricing {
            get {
                return ResourceManager.GetString("enBookApplicationType_ElectronicPricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επιτροπή Κοστολόγησης.
        /// </summary>
        internal static string enBookApplicationType_WelfareCommittee {
            get {
                return ResourceManager.GetString("enBookApplicationType_WelfareCommittee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ολοκληρώθηκε.
        /// </summary>
        internal static string enBookBlackListStatus_Complete {
            get {
                return ResourceManager.GetString("enBookBlackListStatus_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Διαγραμμένη εγγραφή.
        /// </summary>
        internal static string enBookBlackListStatus_Deleted {
            get {
                return ResourceManager.GetString("enBookBlackListStatus_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σε εκκρεμότητα.
        /// </summary>
        internal static string enBookBlackListStatus_Pending {
            get {
                return ResourceManager.GetString("enBookBlackListStatus_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string enBookBlackListStatus_Triggered {
            get {
                return ResourceManager.GetString("enBookBlackListStatus_Triggered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Από ήδη κοστολογημένο βιβλίο.
        /// </summary>
        internal static string enBookContentType_FromAlreadyPricedBook {
            get {
                return ResourceManager.GetString("enBookContentType_FromAlreadyPricedBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Νέο.
        /// </summary>
        internal static string enBookContentType_New {
            get {
                return ResourceManager.GetString("enBookContentType_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σκληρό εξώφυλλο.
        /// </summary>
        internal static string enBookCoverType_Hard {
            get {
                return ResourceManager.GetString("enBookCoverType_Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Μαλακό Εξώφυλλο.
        /// </summary>
        internal static string enBookCoverType_Soft {
            get {
                return ResourceManager.GetString("enBookCoverType_Soft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αποδεκτή.
        /// </summary>
        internal static string enBookPriceRequestState_Accepted {
            get {
                return ResourceManager.GetString("enBookPriceRequestState_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ζητήθηκε Αντίγραφο.
        /// </summary>
        internal static string enBookPriceRequestState_Asked {
            get {
                return ResourceManager.GetString("enBookPriceRequestState_Asked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Νέα.
        /// </summary>
        internal static string enBookPriceRequestState_New {
            get {
                return ResourceManager.GetString("enBookPriceRequestState_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σε πρακτικό.
        /// </summary>
        internal static string enBookPriceRequestState_Record {
            get {
                return ResourceManager.GetString("enBookPriceRequestState_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Μη αποδεκτή.
        /// </summary>
        internal static string enBookPriceRequestState_Rejected {
            get {
                return ResourceManager.GetString("enBookPriceRequestState_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αναθεώρηση.
        /// </summary>
        internal static string enBookPriceRequestState_Review {
            get {
                return ResourceManager.GetString("enBookPriceRequestState_Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δείγμα.
        /// </summary>
        internal static string enBookPriceRequestState_Sample {
            get {
                return ResourceManager.GetString("enBookPriceRequestState_Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Προσωρινή.
        /// </summary>
        internal static string enBookPriceRequestState_Temporary {
            get {
                return ResourceManager.GetString("enBookPriceRequestState_Temporary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ενεργή.
        /// </summary>
        internal static string enBookPriceStatus_Active {
            get {
                return ResourceManager.GetString("enBookPriceStatus_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Διαγραμμένη.
        /// </summary>
        internal static string enBookPriceStatus_Deleted {
            get {
                return ResourceManager.GetString("enBookPriceStatus_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ακυρωμένη.
        /// </summary>
        internal static string enBookPriceStatus_Invalid {
            get {
                return ResourceManager.GetString("enBookPriceStatus_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ηλεκτρονικό.
        /// </summary>
        internal static string enBookType_EPublished {
            get {
                return ResourceManager.GetString("enBookType_EPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κανονικό.
        /// </summary>
        internal static string enBookType_Regular {
            get {
                return ResourceManager.GetString("enBookType_Regular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αυτο-έκδοση.
        /// </summary>
        internal static string enBookType_SelfPublished {
            get {
                return ResourceManager.GetString("enBookType_SelfPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δημιουργία.
        /// </summary>
        internal static string enCatalogGroupLogAction_Create {
            get {
                return ResourceManager.GetString("enCatalogGroupLogAction_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Διαγραφή.
        /// </summary>
        internal static string enCatalogGroupLogAction_Delete {
            get {
                return ResourceManager.GetString("enCatalogGroupLogAction_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επεξεργασία.
        /// </summary>
        internal static string enCatalogGroupLogAction_Edit {
            get {
                return ResourceManager.GetString("enCatalogGroupLogAction_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κλείδωμα.
        /// </summary>
        internal static string enCatalogGroupLogAction_Lock {
            get {
                return ResourceManager.GetString("enCatalogGroupLogAction_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εξαγωγή PDF.
        /// </summary>
        internal static string enCatalogGroupLogAction_PDFPrint {
            get {
                return ResourceManager.GetString("enCatalogGroupLogAction_PDFPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επαναφορά.
        /// </summary>
        internal static string enCatalogGroupLogAction_Rollback {
            get {
                return ResourceManager.GetString("enCatalogGroupLogAction_Rollback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ξεκλείδωμα.
        /// </summary>
        internal static string enCatalogGroupLogAction_Unlock {
            get {
                return ResourceManager.GetString("enCatalogGroupLogAction_Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εγκεκριμένη για πληρωμή.
        /// </summary>
        internal static string enCatalogGroupState_Approved {
            get {
                return ResourceManager.GetString("enCatalogGroupState_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Μη επιλεχθέν.
        /// </summary>
        internal static string enCatalogGroupState_New {
            get {
                return ResourceManager.GetString("enCatalogGroupState_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επιστροφή από ΥΔΕ.
        /// </summary>
        internal static string enCatalogGroupState_Returned {
            get {
                return ResourceManager.GetString("enCatalogGroupState_Returned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επιλεχθέν για πληρωμή.
        /// </summary>
        internal static string enCatalogGroupState_Selected {
            get {
                return ResourceManager.GetString("enCatalogGroupState_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σταλμένη προς ΥΔΕ.
        /// </summary>
        internal static string enCatalogGroupState_Sent {
            get {
                return ResourceManager.GetString("enCatalogGroupState_Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δημιουργία.
        /// </summary>
        internal static string enCatalogLogAction_Create {
            get {
                return ResourceManager.GetString("enCatalogLogAction_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Διαγραφή.
        /// </summary>
        internal static string enCatalogLogAction_Delete {
            get {
                return ResourceManager.GetString("enCatalogLogAction_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επεξεργασία.
        /// </summary>
        internal static string enCatalogLogAction_Edit {
            get {
                return ResourceManager.GetString("enCatalogLogAction_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επαναφορά.
        /// </summary>
        internal static string enCatalogLogAction_Rollback {
            get {
                return ResourceManager.GetString("enCatalogLogAction_Rollback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ακυρωμένη.
        /// </summary>
        internal static string enCatalogState_Canceled {
            get {
                return ResourceManager.GetString("enCatalogState_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Από αντιγραφή.
        /// </summary>
        internal static string enCatalogState_FromMove {
            get {
                return ResourceManager.GetString("enCatalogState_FromMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αντιγραμμένη.
        /// </summary>
        internal static string enCatalogState_Moved {
            get {
                return ResourceManager.GetString("enCatalogState_Moved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κανονική.
        /// </summary>
        internal static string enCatalogState_Normal {
            get {
                return ResourceManager.GetString("enCatalogState_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ενεργή.
        /// </summary>
        internal static string enCatalogStatus_Active {
            get {
                return ResourceManager.GetString("enCatalogStatus_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Διαγραμμένη.
        /// </summary>
        internal static string enCatalogStatus_Deleted {
            get {
                return ResourceManager.GetString("enCatalogStatus_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ακυρωμένη.
        /// </summary>
        internal static string enCatalogStatus_Invalid {
            get {
                return ResourceManager.GetString("enCatalogStatus_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σε στοκ.
        /// </summary>
        internal static string enCatalogStatus_Stock {
            get {
                return ResourceManager.GetString("enCatalogStatus_Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αυτόματη.
        /// </summary>
        internal static string enCatalogType_Automatic {
            get {
                return ResourceManager.GetString("enCatalogType_Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αύξηση αρ. αντιτύπων.
        /// </summary>
        internal static string enCatalogType_IncreasedBooksCount {
            get {
                return ResourceManager.GetString("enCatalogType_IncreasedBooksCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αύξηση Τιμής.
        /// </summary>
        internal static string enCatalogType_IncreasedPrice {
            get {
                return ResourceManager.GetString("enCatalogType_IncreasedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Χειροκίνητη.
        /// </summary>
        internal static string enCatalogType_Manual {
            get {
                return ResourceManager.GetString("enCatalogType_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κανονική.
        /// </summary>
        internal static string enCatalogType_Normal {
            get {
                return ResourceManager.GetString("enCatalogType_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Μείωση αρ. αντιτύπων.
        /// </summary>
        internal static string enCatalogType_ReducedBooksCount {
            get {
                return ResourceManager.GetString("enCatalogType_ReducedBooksCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Μείωση Τιμής.
        /// </summary>
        internal static string enCatalogType_ReducedPrice {
            get {
                return ResourceManager.GetString("enCatalogType_ReducedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αντιλογισμός.
        /// </summary>
        internal static string enCatalogType_Reversal {
            get {
                return ResourceManager.GetString("enCatalogType_Reversal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ειδική.
        /// </summary>
        internal static string enCatalogType_Special {
            get {
                return ResourceManager.GetString("enCatalogType_Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Χειροκίνητη Εισαγωγή.
        /// </summary>
        internal static string enDeductionVatType_Custom {
            get {
                return ResourceManager.GetString("enDeductionVatType_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κανονικό.
        /// </summary>
        internal static string enDeductionVatType_High {
            get {
                return ResourceManager.GetString("enDeductionVatType_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κανονικό νήσων εκτός Κρήτης.
        /// </summary>
        internal static string enDeductionVatType_HighLowered {
            get {
                return ResourceManager.GetString("enDeductionVatType_HighLowered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Μειωμένο.
        /// </summary>
        internal static string enDeductionVatType_Medium {
            get {
                return ResourceManager.GetString("enDeductionVatType_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Μειωμένο νήσων εκτός Κρήτης.
        /// </summary>
        internal static string enDeductionVatType_MediumLowered {
            get {
                return ResourceManager.GetString("enDeductionVatType_MediumLowered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Υπερμειωμένο.
        /// </summary>
        internal static string enDeductionVatType_Small {
            get {
                return ResourceManager.GetString("enDeductionVatType_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Υπερμειωμένο νήσων εκτός Κρήτης.
        /// </summary>
        internal static string enDeductionVatType_SmallLowered {
            get {
                return ResourceManager.GetString("enDeductionVatType_SmallLowered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Απέτυχε.
        /// </summary>
        internal static string enDeliveryStatus_Failed {
            get {
                return ResourceManager.GetString("enDeliveryStatus_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εκκρεμεί.
        /// </summary>
        internal static string enDeliveryStatus_Pending {
            get {
                return ResourceManager.GetString("enDeliveryStatus_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επιτυχής.
        /// </summary>
        internal static string enDeliveryStatus_Successful {
            get {
                return ResourceManager.GetString("enDeliveryStatus_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αναφορά συμβάντος.
        /// </summary>
        internal static string enEmailEntityType_IncidentReport {
            get {
                return ResourceManager.GetString("enEmailEntityType_IncidentReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κανένα.
        /// </summary>
        internal static string enEmailEntityType_None {
            get {
                return ResourceManager.GetString("enEmailEntityType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Προσαρμοσμένο Μήνυμα.
        /// </summary>
        internal static string enEmailType_CustomMessage {
            get {
                return ResourceManager.GetString("enEmailType_CustomMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Επιβεβαίωσης.
        /// </summary>
        internal static string enEmailType_EmailVerification {
            get {
                return ResourceManager.GetString("enEmailType_EmailVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email με κωδικό πρόσβασης.
        /// </summary>
        internal static string enEmailType_ForgotPassword {
            get {
                return ResourceManager.GetString("enEmailType_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Απάντηση σε ερώτημα του χρήστη.
        /// </summary>
        internal static string enEmailType_IncidentReportAnswer {
            get {
                return ResourceManager.GetString("enEmailType_IncidentReportAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δελτίο Ταυτότητας.
        /// </summary>
        internal static string enIdentificationType_ID {
            get {
                return ResourceManager.GetString("enIdentificationType_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κανένα.
        /// </summary>
        internal static string enIdentificationType_None {
            get {
                return ResourceManager.GetString("enIdentificationType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Διαβατήριο.
        /// </summary>
        internal static string enIdentificationType_Passport {
            get {
                return ResourceManager.GetString("enIdentificationType_Passport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string enLegalType_Allocator {
            get {
                return ResourceManager.GetString("enLegalType_Allocator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Νομικό πρόσωπο.
        /// </summary>
        internal static string enLegalType_Legal {
            get {
                return ResourceManager.GetString("enLegalType_Legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Φυσικό Πρόσωπο.
        /// </summary>
        internal static string enLegalType_Person {
            get {
                return ResourceManager.GetString("enLegalType_Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ΄Αγνωστο.
        /// </summary>
        internal static string enLegalType_Unknown {
            get {
                return ResourceManager.GetString("enLegalType_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string enMinistryAuthorization_Admin {
            get {
                return ResourceManager.GetString("enMinistryAuthorization_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Καμία.
        /// </summary>
        internal static string enMinistryAuthorization_None {
            get {
                return ResourceManager.GetString("enMinistryAuthorization_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read-Only.
        /// </summary>
        internal static string enMinistryAuthorization_ReadOnly {
            get {
                return ResourceManager.GetString("enMinistryAuthorization_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εγκρίθηκε.
        /// </summary>
        internal static string enPaymentOrderState_Approved {
            get {
                return ResourceManager.GetString("enPaymentOrderState_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Νέο.
        /// </summary>
        internal static string enPaymentOrderState_New {
            get {
                return ResourceManager.GetString("enPaymentOrderState_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ολοκληρώθηκε.
        /// </summary>
        internal static string enPaymentOrderState_Paid {
            get {
                return ResourceManager.GetString("enPaymentOrderState_Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Έχει επιστραφεί.
        /// </summary>
        internal static string enPaymentOrderState_Returned {
            get {
                return ResourceManager.GetString("enPaymentOrderState_Returned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επιλεγμένο.
        /// </summary>
        internal static string enPaymentOrderState_Selected {
            get {
                return ResourceManager.GetString("enPaymentOrderState_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Στάλθηκε.
        /// </summary>
        internal static string enPaymentOrderState_Sent {
            get {
                return ResourceManager.GetString("enPaymentOrderState_Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κρίσιμη.
        /// </summary>
        internal static string enQueueEntryPriority_Critical {
            get {
                return ResourceManager.GetString("enQueueEntryPriority_Critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Υψηλή.
        /// </summary>
        internal static string enQueueEntryPriority_High {
            get {
                return ResourceManager.GetString("enQueueEntryPriority_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Χαμηλή.
        /// </summary>
        internal static string enQueueEntryPriority_Low {
            get {
                return ResourceManager.GetString("enQueueEntryPriority_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κανονική.
        /// </summary>
        internal static string enQueueEntryPriority_Normal {
            get {
                return ResourceManager.GetString("enQueueEntryPriority_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Απέτυχε.
        /// </summary>
        internal static string enQueueEntryStatus_Failed {
            get {
                return ResourceManager.GetString("enQueueEntryStatus_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εκτελείται.
        /// </summary>
        internal static string enQueueEntryStatus_Running {
            get {
                return ResourceManager.GetString("enQueueEntryStatus_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επιτυχής.
        /// </summary>
        internal static string enQueueEntryStatus_Successful {
            get {
                return ResourceManager.GetString("enQueueEntryStatus_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αποστολή SMS.
        /// </summary>
        internal static string enQueueEntryType_DispatchSms {
            get {
                return ResourceManager.GetString("enQueueEntryType_DispatchSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Συγχρονισμός Server.
        /// </summary>
        internal static string enQueueEntryType_ServerSync {
            get {
                return ResourceManager.GetString("enQueueEntryType_ServerSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ακυρώθηκε.
        /// </summary>
        internal static string enReceiptState_Canceled {
            get {
                return ResourceManager.GetString("enReceiptState_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCELED.
        /// </summary>
        internal static string enReceiptState_Canceled_service {
            get {
                return ResourceManager.GetString("enReceiptState_Canceled_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Διαγραμμένη.
        /// </summary>
        internal static string enReceiptState_Deleted {
            get {
                return ResourceManager.GetString("enReceiptState_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Παραδόθηκε.
        /// </summary>
        internal static string enReceiptState_Delivered {
            get {
                return ResourceManager.GetString("enReceiptState_Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELIVERED.
        /// </summary>
        internal static string enReceiptState_Delivered_service {
            get {
                return ResourceManager.GetString("enReceiptState_Delivered_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Υπολογισμένη.
        /// </summary>
        internal static string enReceiptStatus_Accounted {
            get {
                return ResourceManager.GetString("enReceiptStatus_Accounted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Νέα.
        /// </summary>
        internal static string enReceiptStatus_New {
            get {
                return ResourceManager.GetString("enReceiptStatus_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ολοκληρωμένη.
        /// </summary>
        internal static string enReceiptStatus_Paid {
            get {
                return ResourceManager.GetString("enReceiptStatus_Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Διαχειριστής.
        /// </summary>
        internal static string enReporterType_Administrator {
            get {
                return ResourceManager.GetString("enReporterType_Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Διαχειριστής Συστήματος.
        /// </summary>
        internal static string enReporterType_AdminUser {
            get {
                return ResourceManager.GetString("enReporterType_AdminUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Χρήστη Υποσυστήματος Πληρωμών.
        /// </summary>
        internal static string enReporterType_MinistryPayments {
            get {
                return ResourceManager.GetString("enReporterType_MinistryPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Χρήστης Υποσυστήματος Κοστολόγησης.
        /// </summary>
        internal static string enReporterType_MinistryWelfare {
            get {
                return ResourceManager.GetString("enReporterType_MinistryWelfare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εκδότης.
        /// </summary>
        internal static string enReporterType_Supplier {
            get {
                return ResourceManager.GetString("enReporterType_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Υπουργείο (Πληρωμές).
        /// </summary>
        internal static string enRole_MinistryPayments {
            get {
                return ResourceManager.GetString("enRole_MinistryPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Υπουργείο (Αιτήσεις Κοστολόγησης).
        /// </summary>
        internal static string enRole_MinistryWelfare {
            get {
                return ResourceManager.GetString("enRole_MinistryWelfare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εκδότης.
        /// </summary>
        internal static string enRole_Supplier {
            get {
                return ResourceManager.GetString("enRole_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Διαχειριστής.
        /// </summary>
        internal static string enRole_SystemAdministrator {
            get {
                return ResourceManager.GetString("enRole_SystemAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εαρινό.
        /// </summary>
        internal static string enSemesterType_Spring {
            get {
                return ResourceManager.GetString("enSemesterType_Spring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Χειμερινό.
        /// </summary>
        internal static string enSemesterType_Winter {
            get {
                return ResourceManager.GetString("enSemesterType_Winter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δημιουργήθηκε.
        /// </summary>
        internal static string enSMSStatus_CreatedOnly {
            get {
                return ResourceManager.GetString("enSMSStatus_CreatedOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Απέτυχε.
        /// </summary>
        internal static string enSMSStatus_Failed {
            get {
                return ResourceManager.GetString("enSMSStatus_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Στάλθηκε.
        /// </summary>
        internal static string enSMSStatus_Sent {
            get {
                return ResourceManager.GetString("enSMSStatus_Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Προσαρμοσμένο μήνυμα.
        /// </summary>
        internal static string enSMSType_CustomMessage {
            get {
                return ResourceManager.GetString("enSMSType_CustomMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αποστολή κωδικού επιβεβαίωσης.
        /// </summary>
        internal static string enSMSType_VerificationCode {
            get {
                return ResourceManager.GetString("enSMSType_VerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ενεργός.
        /// </summary>
        internal static string enSupplierStatus_Active {
            get {
                return ResourceManager.GetString("enSupplierStatus_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ανενεργός.
        /// </summary>
        internal static string enSupplierStatus_Inactive {
            get {
                return ResourceManager.GetString("enSupplierStatus_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ακυρωμένος.
        /// </summary>
        internal static string enSupplierStatus_Invalid {
            get {
                return ResourceManager.GetString("enSupplierStatus_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ηλεκτρονικός Εκδότης.
        /// </summary>
        internal static string enSupplierType_EbookPublisher {
            get {
                return ResourceManager.GetString("enSupplierType_EbookPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Νομικό Πρόσωπο.
        /// </summary>
        internal static string enSupplierType_LegalPerson {
            get {
                return ResourceManager.GetString("enSupplierType_LegalPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Φυσικό Πρόσωπο.
        /// </summary>
        internal static string enSupplierType_SelfPublisher {
            get {
                return ResourceManager.GetString("enSupplierType_SelfPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εγκρίθηκε.
        /// </summary>
        internal static string enWelfareRecordEntryState_Approved {
            get {
                return ResourceManager.GetString("enWelfareRecordEntryState_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τελική.
        /// </summary>
        internal static string enWelfareRecordEntryState_Final {
            get {
                return ResourceManager.GetString("enWelfareRecordEntryState_Final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τροποποιήθηκε.
        /// </summary>
        internal static string enWelfareRecordEntryState_Modified {
            get {
                return ResourceManager.GetString("enWelfareRecordEntryState_Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Νέα.
        /// </summary>
        internal static string enWelfareRecordEntryState_New {
            get {
                return ResourceManager.GetString("enWelfareRecordEntryState_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ένσταση.
        /// </summary>
        internal static string enWelfareRecordEntryState_Objection {
            get {
                return ResourceManager.GetString("enWelfareRecordEntryState_Objection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ζητήθηκε Αντίγραφο.
        /// </summary>
        internal static string enWelfareRecordEntryState_Postponed {
            get {
                return ResourceManager.GetString("enWelfareRecordEntryState_Postponed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Απορρίφθηκε.
        /// </summary>
        internal static string enWelfareRecordEntryState_Rejected {
            get {
                return ResourceManager.GetString("enWelfareRecordEntryState_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σε Εκκρεμότητα.
        /// </summary>
        internal static string enWelfareRecordEntryState_Suspended {
            get {
                return ResourceManager.GetString("enWelfareRecordEntryState_Suspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αποδεκτό.
        /// </summary>
        internal static string enWelfareRecordState_Approved {
            get {
                return ResourceManager.GetString("enWelfareRecordState_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Διαγραμμένο.
        /// </summary>
        internal static string enWelfareRecordState_Deleted {
            get {
                return ResourceManager.GetString("enWelfareRecordState_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Νέο.
        /// </summary>
        internal static string enWelfareRecordState_New {
            get {
                return ResourceManager.GetString("enWelfareRecordState_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ολοκληρωμένο.
        /// </summary>
        internal static string enWelfareRecordState_Priced {
            get {
                return ResourceManager.GetString("enWelfareRecordState_Priced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επιστροφή από Επιτροπή.
        /// </summary>
        internal static string enWelfareRecordState_Returned {
            get {
                return ResourceManager.GetString("enWelfareRecordState_Returned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Στάλθηκε.
        /// </summary>
        internal static string enWelfareRecordState_Sent {
            get {
                return ResourceManager.GetString("enWelfareRecordState_Sent", resourceCulture);
            }
        }
    }
}
