//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace EudoxusOsy.Portal.UserControls.ExportGridViews {
    
    
    public partial class EditCatalogsExportGridView {
        
        /// <summary>
        /// gvEditCatalogs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxGridView gvEditCatalogs;
        
        /// <summary>
        /// gveEditCatalogs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxGridViewExporter gveEditCatalogs;
    }
}
