//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace EudoxusOsy.Portal.Secure.Ministry {
    
    
    public partial class SearchSuppliers {
        
        /// <summary>
        /// btnExportSuppliers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxButton btnExportSuppliers;
        
        /// <summary>
        /// btnExportCoAuthors control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxButton btnExportCoAuthors;
        
        /// <summary>
        /// btnExportSuppliersNoLogisticBooks control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxButton btnExportSuppliersNoLogisticBooks;
        
        /// <summary>
        /// btnExportCommitmentsRegistry control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxButton btnExportCommitmentsRegistry;
        
        /// <summary>
        /// ucSearchFilters control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EudoxusOsy.Portal.UserControls.SearchFilters.SupplierSearchFiltersControl ucSearchFilters;
        
        /// <summary>
        /// btnSearch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxButton btnSearch;
        
        /// <summary>
        /// gvSuppliers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EudoxusOsy.Portal.UserControls.GridViews.SuppliersGridView gvSuppliers;
        
        /// <summary>
        /// gvSuppliersExport control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EudoxusOsy.Portal.UserControls.ExportGridViews.SuppliersExportGridView gvSuppliersExport;
        
        /// <summary>
        /// odsSuppliers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ObjectDataSource odsSuppliers;
    }
}
